version: '3'

services:
  api:
    restart: always
    build: ./publish
    ports:
      - "8977:80"
    depends_on:
      - mysql
  mysql:
    restart: always
    image: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=54602
      - MYSQL_DATABASE=itsupport
    volumes:
      - mysql_data:/var/lib/mysql
  adminer:
    restart: always
    image: adminer
    ports:
      - "8888:8080"
volumes:
  mysql_data: